spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msb_dongbao_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8 #mysql连接
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  security:
    user:
      name: root
      password: 123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/com/msb/dongbao/ums/mapper/xml/*.xml #扫描xml文件
  type-aliases-package: com.msb.dongbao.ums.entity